### ISSUE TITLE
GeoStats.jl docs not linked correctly

### ISSUE THREAD

**Issue by juliohm** [JuliaDocs/DocumentationGenerator.jl#108]
The link in pkg.julialang.org does not point to the correct docs. The correct link is https://juliaearth.github.io/GeoStats.jl/stable/

**Comment by juliohm** [comment]
Appreciate if someone can take a look at this.

**Comment by pfitzseb** [comment]
We don't automatically link against your docs unless you put an entry into https://github.com/JuliaDocs/DocumentationGeneratorRegistry.

Also note that the pkg.julialang.org will go down in it's current form in the next few days.
