### ISSUE TITLE
DynamicHMC.jl does not show up at pkg.julialang.org/docs/

### ISSUE THREAD

**Issue by tpapp** [JuliaDocs/DocumentationGenerator.jl#11]
I am the author, let me know if there is anything I can fix on my end.

repo: https://github.com/tpapp/DynamicHMC.jl

**Comment by pfitzseb** [comment]
I'm pretty sure this is an issue on our side. Will investigate.

**Comment by pfitzseb** [comment]
Closed in favour of https://github.com/JuliaDocs/DocumentationGenerator.jl/issues/15.
