### ISSUE TITLE
ReactionNetworkImporters.jl not showing up 

### ISSUE THREAD

**Issue by isaacsas** [JuliaDocs/DocumentationGenerator.jl#12]
As requested from Slack, I'm just posting that my package, ReactionNetworkImporters.jl, which is in METADATA and the general registry doesn't seem to be showing up at pkg.julialang.org. Note, I have no docs for the package (but do have a README, and just added tags).

Feel free to close if this is redundant with other issues.

**Comment by pfitzseb** [comment]
Ok, so the reason this particular package doesn't show up is because it's not compatible with Julia 1.0 which we still use to build the site.

**Comment by pfitzseb** [comment]
Closed in favour of https://github.com/JuliaDocs/DocumentationGenerator.jl/issues/15.
