### ISSUE TITLE
Empty docstrings

### ISSUE THREAD

**Issue by GunnarFarneback** [JuliaDocs/DocumentationGenerator.jl#14]
In the Docstrings section it's not very enlightening to list all functions without docstrings. For example in my Inflate package I have deliberately chosen to have docstrings only for the exported functions. I would suggest removing all functions without docstrings from the Docstrings list.

Also regardless of docstrings there's little point listing the `eval` and `include` functions that automatically exist in every module.

**Comment by christianpeel** [comment]
If for some reason you don't follow Gunnar' suggest, at least only try to show docstrings for exported functions only.  Trying to show docstrings for unexported functions makes most packages look poorly-documented.

**Comment by pfitzseb** [comment]
This a somewhat tricky problem, because a packages official API is not generally identical to the set of exported functions _or_ the set of functions with docstrings. The proper solution to this is of course to introduce some way to mark a binding as part of the API, but we don't have that yet.

So the most conservative options would be to only show exported _and_ documented bindings here, but not that seems bad for discoverability.

**Comment by mcabbott** [comment]
I think some un-exported functions do deserve to be included, some packages choose to export little or nothing, or use the same names as in Base. 

But some un-exported functions could be omitted. Perhaps all those without docstrings? I also wonder whether the some convention like being named `_fun` might exclude a function, even if you have written a docstring as a comment to remind yourself what it does.

**Comment by christianpeel** [comment]
Thanks for explanations. I'd also like to have functions without docstrings omitted.

**Comment by SimonDanisch** [comment]
The easiest way to do that is to actually supply a docs/make.jl ;) 
The magic documentation generation is really just a crude fallback for packages that don't use Documenter - which most packages that want nice docs should adept ;) 
With `DocumentationGenerator`, you don't even need to worry about hosting etc, as long as you have a working `docs/make.jl` :)

**Comment by mcabbott** [comment]
That sounds good. Is there an example of a really simple `docs/make.jl` somewhere, which just tweaks what DocumentationGenerator does? 

There are useful-sounding commands in the [Documenter docs](https://juliadocs.github.io/Documenter.jl/stable/man/syntax/) but they seem to need to be in a `.md` file. The linked examples ([e.g.](https://github.com/queryverse/Query.jl/blob/master/docs/make.jl)) all seem to do more elaborate things, not just readme + (filtered) docstrings.

**Comment by GunnarFarneback** [comment]
The question here is really not whether there are ways to make sure that your own docs look good but what defaults will best serve the Julia community for the packages that don't do that for one reason or another.
* Rendering the README - great idea.
* Listing exported functions with docstrings - good idea.
* Listing exported functions without docstrings - maybe good idea.
* Listing non-exported functions with docstrings - probably good idea.
* Listing non-exported functions without docstrings - useless and distracting.
* Listing the mandatory eval and include functions - pointless in the extreme.

**Comment by pfitzseb** [comment]
Alright, this should be fixed now -- we're only listing what a standard Documenter `@autodocs` block shows (so all functions with docstrings).
