### ISSUE TITLE
Docs failed for MixedModels

### ISSUE THREAD

**Issue by vdayanand** [JuliaDocs/DocumentationGenerator.jl#147]
https://juliahub.com/ui/Logs/docs/MixedModels/tBiYK/2.3.0.log?refresh=30000

**Comment by pfitzseb** [comment]
That's an issue with their docs -- they're trying to include [`constructors.md`](https://github.com/JuliaStats/MixedModels.jl/blob/v2.3.0/docs/make.jl), but that file doesn't exist: https://github.com/JuliaStats/MixedModels.jl/tree/v2.3.0/docs/src.

Nothing we can do about that.

The bigger issue is that there's no readme...
