### ISSUE TITLE
Package not showing up on pkg.julialang.org

### ISSUE THREAD

**Issue by pfitzseb** [JuliaDocs/DocumentationGenerator.jl#15]
If you're a package author and your package is missing from pkg.julialang.org, please post a comment here and I'll add it to this post.

- [x]  https://github.com/tpapp/DynamicHMC.jl -- works locally, added to tests
- [x] https://github.com/thofma/Hecke.jl -- works locally, added to tests
- [x] https://github.com/isaacsas/ReactionNetworkImporters.jl -- works locally, added to tests
- [x] QuantEcon.jl
- [x] GeoStats.jl -- is there but only shows fallback docs

**Comment by vdayanand** [comment]
Hecke.jl is now available

**Comment by vdayanand** [comment]
DynamicHMC is available

**Comment by arnavs** [comment]
QuantEcon/QuantEcon.jl

**Comment by juliohm** [comment]
GeoStats.jl

**Comment by vdayanand** [comment]
GeoStats : https://pkg.julialang.org/docs/GeoStats/ce7nU/0.8.6/

**Comment by juliohm** [comment]
Thanks @vdayanand the package is listed now. The link to the documentation is incorrect though. It is pointing to a generated documentation from the README instead of pointing to the already built documentation with Documenter.jl

**Comment by vdayanand** [comment]
@juliohm We have fixed with the latest deployment

**Comment by vdayanand** [comment]
ReactionNetworkImporters.jl  is now available

**Comment by vdayanand** [comment]
Looks like we still have issues with `QuantEcon.jl` 0.15.0
``` 

┌ Error: Tried building Documenter.jl docs but failed.
│   error =
│    MethodError: no method matching mdflatten(::Base.GenericIOBuffer{Array{UInt8,1}}, ::typeof(\), ::Markdown.Paragraph)
│    Closest candidates are:
│      mdflatten(::Any, !Matched::Markdown.MD, ::Any) at /root/.juliapro/JuliaPro_v1.1.0.1/packages/Documenter/J3Jag/src/Utilities/MDFlatten.jl:33
│      mdflatten(::Any, !Matched::Markdown.Paragraph, ::Any) at /root/.juliapro/JuliaPro_v1.1.0.1/packages/Documenter/J3Jag/src/Utilities/MDFlatten.jl:45
│      mdflatten(::Any, !Matched::Markdown.BlockQuote, ::Any) at /root/.juliapro/JuliaPro_v1.1.0.1/packages/Documenter/J3Jag/src/Utilities/MDFlatten.jl:46
│      ...
└ @ Main ~/PkgSync/DocumentationGenerator/src/worker_work.jl:35
[ Info: Building default docs.
[ Info: SetupBuildDirectory: setting up build directory.
[ Info: ExpandTemplates: expanding markdown templates.

 Resolving package versions...
  Updating `/tmp/tmprWYr45/Project.toml`
 [no changes]
  Updating `/tmp/tmprWYr45/Manifest.toml`
 [no changes]

┌ Warning: no do
```

**Comment by s-broda** [comment]
[ARCHModels.jl](https://github.com/s-broda/ARCHModels.jl) is only showing the readme.md fallback, see [here](https://pkg.julialang.org/docs/ARCHModels/cpjxl/0.4.0/).

**Comment by juliohm** [comment]
Interestingly, pkg.julialang.org is erasing the CSS style I have chosen for my docs.

**Comment by pfitzseb** [comment]
That's a separate issue. Can you open one with a few additional details (most importantly which repo we're talking about)?

**Comment by juliohm** [comment]
Yes. I'm far from my computer at the moment, but the package is GeoStats.jl

**Comment by arnavs** [comment]
@vdayanand Any luck with https://github.com/QuantEcon/QuantEcon.jl? 

Let us know if there are any changes you need us to make.

**Comment by mortenpi** [comment]
FWIW, I think the GeoStats issue comes from here

https://github.com/JuliaDocs/DocumentationGenerator.jl/blob/a1406fae14263ab5787323c7bc264a5e437f6e10/src/DocumentationGenerator.jl#L218-L220

which is removing custom `assets` arguments (cf. [GeoStats `make.jl`](https://github.com/juliohm/GeoStats.jl/blob/a04dd3fcee6250c592c23b8802e1765e368c78b5/docs/make.jl#L14)).

**Comment by vdayanand** [comment]
@arnavs latest release of QuantEcon is now hosted

**Comment by arnavs** [comment]
Awesome, thank you @vdayanand!

**Comment by s-broda** [comment]
ARCHModels.jl is still just showing the readme, not the docs, as mentioned in https://github.com/JuliaDocs/DocumentationGenerator.jl/issues/15#issuecomment-505432592.

**Comment by ericphanson** [comment]
My little [TravelingSalesmanExact](https://github.com/ericphanson/TravelingSalesmanExact.jl/) doesn’t seem to be showing up.
