### ISSUE TITLE
Total number of packages and a browsable list

### ISSUE THREAD

**Issue by ViralBShah** [JuliaDocs/DocumentationGenerator.jl#21]
It would be really valuable to have a total number of packages on the landing page for pkg.julialang.org and a directory or some kind of browsable list of all packages linked from the landing page.

**Comment by pfitzseb** [comment]
Total number of packages is in the lower right corner:
![image](https://user-images.githubusercontent.com/6735977/56082592-e4a9ba80-5e1a-11e9-9dd5-a2059e2b5df5.png)

Could definitely be more visible though. Not sure what you mean by "browsable list of all packages" -- isn't that precisely what pkg.julialang.org is?

**Comment by ViralBShah** [comment]
It would be nice to show the number of packages more prominently.

With browsable, I meant a listing somewhere (not the landing page) which lists all the 1,774 packages in one page (with less information). Sometimes I just like seeing (personally) the full list of packages in one place.

**Comment by ViralBShah** [comment]
This is just me submitting what I think I might like, and I will let the folks building decide whether it's a good idea or not.

**Comment by aviks** [comment]
I would propose we leave things as they are, in terms of this request. All the information you request is already displayed, albeit in a slightly different fashion.
