### ISSUE TITLE
Enable a stable URL for a package's documentation

### ISSUE THREAD

**Issue by christianpeel** [JuliaDocs/DocumentationGenerator.jl#29]
In discourse, Stefan [said](https://discourse.julialang.org/t/new-pkg-julialang-org/22622) that the new package system "...removes the burden from package developers of figuring out how to host docs and provide search functionality."  I like this; I don't want to host package documentation, and I think it would be valuable to have all the documentation in a single place.   One thing that would facilitate this is having a stable per-package URL that package creators can link to from their package github page.  

I made the package [LLLplus](https://github.com/christianpeel/LLLplus.jl). I updated it recently to v1.2.0, and the new docs are available at https://pkg.julialang.org/docs/LLLplus/zQjW4/1.2.0/  I'd like to be able to link to either https://pkg.julialang.org/docs/LLLplus (or maybe a URL ending in "latest") from a "docs" button on my package page  and have that redirect to the latest manual for my package.   Unfortunately I can't do that now, because https://pkg.julialang.org/docs/LLLplus gives me a 'Forbidden' error.

**Comment by pfitzseb** [comment]
We're working on it -- the current plan is something like

1.  https://pkg.julialang.org/docs/IJulia/ -> symlinked to latest version (if that's the only package in General with that name)
2.  https://pkg.julialang.org/docs/IJulia/nfu7T/ -> symlinked to latest version
3.  https://pkg.julialang.org/docs/IJulia/nfu7T/stable -> symlinked to latest version
4.  https://pkg.julialang.org/docs/IJulia/nfu7T/0.8 -> symlinked to latest 0.8.x patch release
5.  https://pkg.julialang.org/docs/IJulia/nfu7T/0.8.3

Still not totally sure about the first and last points: 1) means that the first package registered with a name gets a prettier URL than others, and 5) means keeping around *all* previous docs, which might very well blow up in size.

**Comment by fredrikekre** [comment]
FWIW I don't think we have come to an agreement whether allowing multiple packages with the same name in General.
Also, if we have 2, whats the point of 3?

**Comment by pfitzseb** [comment]
> FWIW I don't think we have come to an agreement whether allowing multiple packages with the same name in General.

Fair enough.

> Also, if we have 2, whats the point of 3?

Consistency with Documenter's output? It's redundant, but that's not necessarily a bad thing.

**Comment by fredrikekre** [comment]
> Consistency with Documenter's output? It's redundant, but that's not necessarily a bad thing.

Documenter does not have this though: e.g. https://fredrikekre.github.io/Literate.jl/ vs https://fredrikekre.github.io/Literate.jl/stable

**Comment by pfitzseb** [comment]
Right you are, my bad. I should also add that the above is in no way set in stone, so if anyone has other suggestions we'd love to read them.

**Comment by StefanKarpinski** [comment]
> FWIW I don't think we have come to an agreement whether allowing multiple packages with the same name in General.

I'm all for it—and of course it was an explicit design goal to allow it. Combined with the fact that it's now much easier to rename packages, it massively alleviates the pressure to pick the best possible name up front. If you decide you want a different name later, just rename! If some old, abandoned packager name-squatted a great name, no problem, just register a new package with the same name. Of course, we need to make sure that there is a good UI to make sure that users get the package they actually wanted, but two packages with the same name is just an extreme case of typo squatting, which we want to [defend against](https://github.com/JuliaLang/Pkg.jl/issues/931) anyway.

**Comment by StefanKarpinski** [comment]
> 1) means that the first package registered with a name gets a prettier URL than others

I'm not sure it has to mean that, I think that it should only be a temporary redirect to the full package URL when there's only a single package by that name; as soon as someone registers a second package with the same name, the page should become a disambiguation page listing all the packages with that name from most to least popular, with enough information to choose between them. In this arrangement, there's no first-registered advantage. Does that make sense?

**Comment by StefanKarpinski** [comment]
E.g. I'd like to never need to have conversations [like this](https://github.com/JuliaRegistries/General/pull/174) where we tell people that they need to call their package something different. Allowing multiple registered packages to have the same name seems like an essential part of not worrying about what people call their packages.

**Comment by pfitzseb** [comment]
> I'm not sure it has to mean that, I think that it should only be a temporary redirect to the full package URL when there's only a single package by that name; as soon as someone registers a second package with the same name, the page should become a disambiguation page listing all the packages with that name from most to least popular, with enough information to choose between them. In this arrangement, there's no first-registered advantage. Does that make sense?

It does, but it also means that the URL *isn't* really stable in the sense that `https://pkg.julialang.org/docs/IJulia/foo/bar` would redirect to the disambiguation page instead of the correct target.

**Comment by StefanKarpinski** [comment]
Right, I would propose that `https://pkg.julialang.org/docs/IJulia` be a [302 redirect](https://en.wikipedia.org/wiki/HTTP_302) to `https://pkg.julialang.org/docs/IJulia/nfu7T/` so that the URL in the browser if someone copies it is the full disambiguated one.

**Comment by christianpeel** [comment]
One simple solution to name collision would be to re-use the GitHub namespace.  I.e.  IJulia documentation would be at  https://pkg.julialang.org/docs/JuliaLang/IJulia.jl  and JuMP would be at https://pkg.julialang.org/docs/JuliaOpt/JuMP.jl   Is it a goal to support packages that are not on GitHub?

**Comment by StefanKarpinski** [comment]
Oh, that's a nice idea! It would potentially change if a package changes orgs, but that's maybe not such a big deal. We don't want to be tied to GitHub, but the notion of user/org names can be generalized to other code platforms. There's the outside corner case of the same user name and package name on different platforms, but I think we can just disallow that case.

**Comment by christopher-dG** [comment]
Why not pkg.julialang.org/docs/gh/user/repo?
gh for GitHub, gl for GitLab, bb for BitBucket.
Could also set up a redirect for when there's only one user/repo package.

**Comment by StefanKarpinski** [comment]
So the permanent URL of a package is tied to where it happens to be hosted? That seems not great. What if someone decides they want to move their packages (or even an entire org) from GitHub to GitLab, for example? Then all the “permanent” links have to change. I have to say that as much as they’re not the prettiest, the absolute permanence of the five char slugs after the package name still make them the most appealing option to me.

**Comment by christopher-dG** [comment]
As long as there is some "plaintext" URL that properly redirects, I don't really have strong feelings. But I very much want to be able to link to my packages' documentation without knowing a random string.

**Comment by vdayanand** [comment]
its is now possible to access documentation with package name: For eg: [pkg.julialang.org/docs/Flux](https://pkg.julialang.org/docs/Flux)

**Comment by christianpeel** [comment]
Wonderful!  That's all I wanted.  Thanks!
