### ISSUE TITLE
Package headlines should be links

### ISSUE THREAD

**Issue by fredrikekre** [JuliaDocs/DocumentationGenerator.jl#32]
It is annoying that you can't click `JuliaLang/Example` here:
![Screenshot from 2019-05-03 11-04-29](https://user-images.githubusercontent.com/11698744/57128339-5e3a2600-6d93-11e9-8b67-2fec4ae66aa1.png)

**Comment by pfitzseb** [comment]
Where do you want those to go?

My plans for this were to link to package specific sites like [this](https://www.npmjs.com/package/xterm) with some metadata and the readme.

**Comment by fredrikekre** [comment]
> Where do you want those to go?

Doesn't matter, I am just annoyed it doesn't lead anywhere :)

> My plans for this were to link to package specific sites like this with some metadata and the readme.

Yea, that looks nice. Maybe for now link to the repo? Depending on how far in the future this is.
