### ISSUE TITLE
Tag search on Chrome android inserts empty tag

### ISSUE THREAD

**Issue by baggepinnen** [JuliaDocs/DocumentationGenerator.jl#33]
While searching for a tag and clicking a tag, the list of packages updates in the background. When trying to hide the left search column to reveal the found packages, another, empty tag is inserted and the list of found packages becomes empty.

This occurs on Chrome android. Let me know of this proves hard to reproduce and I'll try to upload some screenshots somewhere. It has happened on my phone every time since my first visit at the new site.

**Comment by pfitzseb** [comment]
I can repro this, thanks for the report!

**Comment by pfitzseb** [comment]
Should be fixed with https://github.com/JuliaDocs/DocumentationGenerator.jl/commit/6b4c317f91e9f9948cb520bbbdc4e68986e90d06.
