### ISSUE TITLE
Markdown for strikethrough ~~ renders incorrectly

### ISSUE THREAD

**Issue by baggepinnen** [JuliaDocs/DocumentationGenerator.jl#34]
The github markdown to produce ~~strikethrough text~~ `~~text~~` does not render correctly, it renders verbatim. See e.g. [here](https://pkg.julialang.org/docs/MonteCarloMeasurements/tHYBD/0.2.1/#Multivariate-particles-1)

**Comment by pfitzseb** [comment]
Actually, it might make sense to pre-process readmes on our end so that we can handle this case and inline html correctly.

**Comment by pfitzseb** [comment]
Fixed by https://github.com/JuliaDocs/DocumentationGenerator.jl/pull/42.
