### ISSUE TITLE
Dropdown to select version not working

### ISSUE THREAD

**Issue by baggepinnen** [JuliaDocs/DocumentationGenerator.jl#35]
In the left search column, there is a dropdown menu to select package version to show docs for. It only shows the latest version, even if one can manually navigate to other versions by changing the version number in the URL.
Example
https://pkg.julialang.org/docs/JuliaInterpreter/PliIn/0.5.0/
https://pkg.julialang.org/docs/JuliaInterpreter/PliIn/0.5.1/
both exist, but only 0.5.1 is shown in the dropdown

**Comment by vdayanand** [comment]
Currently we support only the latest release version.
