### ISSUE TITLE
CSS broken if you go to a package URL without version part

### ISSUE THREAD

**Issue by oxinabox** [JuliaDocs/DocumentationGenerator.jl#45]
This is related to #29, in that I was trying to get to the latest URL,
and so tried just deleting the version part.
It would be resolved by just making this a full HTTP redirect.

the CSS is broken if you do not include the version number
See
https://pkg.julialang.org/docs/NamedDims/EBrgX/
vs
https://pkg.julialang.org/docs/NamedDims/EBrgX/0.2.0/
The problem is that stylesheet links to sheets given `assets` below are relative paths,
those `asset` folders exist in the version subdirectory
```
<link href="assets/documenter.css" rel="stylesheet" type="text/css">
```

so displaying same content from different endpoint breaks them.

**Comment by fredrikekre** [comment]
https://pkg.julialang.org/docs/NamedDims/EBrgX/ should probably just redirect.

**Comment by pfitzseb** [comment]
Fixed now.
