### ISSUE TITLE
Filter Docs by Project Manifest

### ISSUE THREAD

**Issue by jessebett** [JuliaDocs/DocumentationGenerator.jl#51]
Would be cool if I could supply a project manifest to the filer list so search and package display only considers project relevant packages.

**Comment by pfitzseb** [comment]
Uploading a manifest seems like a somewhat weird interface, but we definitely need to have a way to only search the docs/code of a subset of packages.

**Comment by jessebett** [comment]
I'm thinking it might be a weird interface to supply the manifest on the web. But maybe something like `] docs` which would produce the url with the filter list already populated from the project manifest?
