### ISSUE TITLE
Request: Include download numbers

### ISSUE THREAD

**Issue by miguelraz** [JuliaDocs/DocumentationGenerator.jl#52]
The rust crates.io includes a download number at the bottom. 
https://crates.io/crates/rand
Adding this interface could help finding packages as well as evidence of use for maintainers, which can help seek funds.

**Comment by aviks** [comment]
Unfortunately, only github knows our download numbers, and they ain't telling :(. We'll need to find a solution to that problem before we can think of displaying them.
