### ISSUE TITLE
Consider not hosting the julia docs

### ISSUE THREAD

**Issue by fredrikekre** [JuliaDocs/DocumentationGenerator.jl#56]
It is, IMO, unfortunate that Julia's docs are hosted at pkg.julialang.org. We should have one canonical place for the base documentation. Could we just build a search-index and link to the official docs instead of also hosting them?

**Comment by StefanKarpinski** [comment]
I do think that’s probably the way to go.

**Comment by mortenpi** [comment]
Hmm, one issue at the moment is that DocumentationGenerator publishes the local build, not the deploy one -- so pretty URLs are off and there are no canonical URL tags. In principle, if the canonical URLs would still be pointing to the main manual, the pkg.julialang.org manual should not show up in search results at least.

**Comment by pfitzseb** [comment]
So lets decide on how to handle https://github.com/JuliaDocs/DocumentationGenerator.jl/pull/36 and we get that for free, basically.
