### ISSUE TITLE
Provide option to opt-out of doc hosting

### ISSUE THREAD

**Issue by davidanthoff** [JuliaDocs/DocumentationGenerator.jl#60]
I want users to always end up at the official Query.jl and friend docs at https://www.queryverse.org/Query.jl/stable/, not a copy hosted somewhere else. What pkg.julialang.org does right now feels a bit like hijacking of docs :) Would be good to have a simple way to opt-out.

I also think it would be good if that was implemented rather sooner than later.

**Comment by pfitzseb** [comment]
https://github.com/JuliaDocs/DocumentationGenerator.jl/pull/36 is almost ready (once we've decided which approach to take, that is), and after that you can add
```
method = "hosted"
location = "https://url.toyour.docs"
```
either to your Project.toml or to a central registry.

**Comment by pfitzseb** [comment]
Can you give https://github.com/JuliaDocs/DocumentationGeneratorRegistry a go? The PR that uses that registry isn't merged yet, but would be good to see if that workflow etc makes sense.

**Comment by davidanthoff** [comment]
https://github.com/JuliaDocs/DocumentationGeneratorRegistry/pull/4

Wouldn't it be easier if I could specify this info inside each root package repo?

**Comment by pfitzseb** [comment]
Take a look at the discussion in https://github.com/JuliaDocs/DocumentationGenerator.jl/pull/36.

**Comment by fredrikekre** [comment]
It's just *really* weird to configure outside applications from within the repository IMO.

**Comment by davidanthoff** [comment]
But wouldn't a config value that points towards the docs for a package be useful far beyond that one app that generates the pkg.julialang.org page? For example, the VS Code extension could potentially use such a host URL to resolve links in inline markdown documentation, and I'm pretty sure the info where the docs for a package are located would be useful in other contexts as well.
