### ISSUE TITLE
URL query parameters for package search

### ISSUE THREAD

**Issue by mortenpi** [JuliaDocs/DocumentationGenerator.jl#62]
So that you could link to an exact package search (i.e. when searching by name and/or tag). I guess something like `https://pkg.julialang.org/docs/?q=foo&tags=bar,baz`.

Not sure how useful it would be, but when opening #61, my initial reaction was to just drop a link to the exact query I made.

**Comment by pfitzseb** [comment]
Yeah, this is planned.
In the (hopefully not too distant) future we'll also have support actual searches in the packages you've filtered.
