### ISSUE TITLE
GeoStats.jl CSS style is ignored

### ISSUE THREAD

**Issue by juliohm** [JuliaDocs/DocumentationGenerator.jl#63]
FWIW, I think the GeoStats issue comes from here

https://github.com/JuliaDocs/DocumentationGenerator.jl/blob/a1406fae14263ab5787323c7bc264a5e437f6e10/src/DocumentationGenerator.jl#L218-L220

which is removing custom `assets` arguments (cf. [GeoStats `make.jl`](https://github.com/juliohm/GeoStats.jl/blob/a04dd3fcee6250c592c23b8802e1765e368c78b5/docs/make.jl#L14)).

_Originally posted by @mortenpi in https://github.com/JuliaDocs/DocumentationGenerator.jl/issues/15#issuecomment-505614393_

**Comment by pfitzseb** [comment]
Ah, true, I forgot we nix all arguments.
Question is whether we *should* support custom styling -- I'm leaning towards yes. What does everyone think?

**Comment by fredrikekre** [comment]
This one in particular seems to be an easy fix, but for more elaborate stuff maybe we can just point people to use their own hosting via #36

**Comment by mortenpi** [comment]
> Question is whether we should support custom styling

I also think yes, at least at the moment. The `assets` keyword should not be nixed at the moment. While losing a custom theme should not break anything, some packages may be using `assets` to include additional JS and CSS dependencies which may actually break some things (don't know how common that is in practice though).

However, I want to re-visit the way assets, themes etc. are handled in Documenter anyway. So we can re-design the API in Documenter in a way to better support DocumentationGenerator too.

> for more elaborate stuff maybe we can just point people to use their own hosting via #36

Does custom hosting integrate with the ecosystem-wide search though?

**Comment by pfitzseb** [comment]
> Does custom hosting integrate with the ecosystem-wide search though?

Yes, as long as you provide an url that lets us find your package's search index.

**Comment by juliohm** [comment]
Could you please share an update regarding this issue?
