### ISSUE TITLE
Docs for Nemo look weird

### ISSUE THREAD

**Issue by thofma** [JuliaDocs/DocumentationGenerator.jl#80]
https://pkg.julialang.org/docs/Nemo/SPUMD/0.9.1 does not look like http://nemocas.github.io/Nemo.jl/latest/

**Comment by mortenpi** [comment]
It's probably because [Nemo requires Documenter 0.19](https://github.com/Nemocas/Nemo.jl/blob/master/docs/Project.toml), but DocumentationGenerator uses a newer version (if I remember correctly, it does not honor `docs/Project.toml`).

**Comment by pfitzseb** [comment]
That seems likely. Will take a stab at implementing the "proper" way this week.
