### ISSUE TITLE
Documentation mismatch between Github pages and pkg.julialang.org

### ISSUE THREAD

**Issue by jagot** [JuliaDocs/DocumentationGenerator.jl#99]
For some reason, the documentation [hosted on pkg.julialang.org](https://pkg.julialang.org/docs/SolverTraces/mHUHm/0.1.0) does not match the one [hosted by Github](https://jagot.github.io/SolverTraces.jl/stable). There seems to be a mismatch between Documenter versions, which could be the reason (?).

CC @mortenpi

**Comment by pfitzseb** [comment]
No, this isn't related to Documenter at all.
We probably were running into an error while building the docs on our server and fell back to the basic readme docs. Will look into why this was happening.
